import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js";
import Stats from "/components/Stats/Stats.js"
import Team from "/components/Team/Team.js"

export default function About() {
    return (
      <div>
         <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'About Us'}></Header>
          <Stats />
          <Team />
          <Fotter />
      </div>
    )
  }