import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js"

export default function careers() {
    return (
      <div>
         <Head>
          <title>Careers</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'Careers'}></Header>
          
          <Fotter />
      </div>
    )
  }