import Head from 'next/head'
import Navbar from "../components/Navbar/NavbarElement.js"
import Header from "../components/Header/HeaderElement.js"
import Fotter from "../components/Fotter/Fotter.js"
import Contact from "../components/ContactUs/ContactUs.js"

export default function ContactUs() {
    return (
      <div>
         <Head>
          <title>Contact Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'Contact Us'}></Header>
          <Contact />
          <Fotter />
      </div>
    )
  }