import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js";
import SilentFeatures from "/components/Curriculum/CurriculumElement.js"

export default function curriculum() {
    return (
      <div>
         <Head>
          <title>Curriculum</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'Curriculum'}></Header>
          <SilentFeatures />
          <Fotter />
      </div>
    )
  }