import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js"
import FacultyTable from "/components/Faculty/FacultyTable.js"

export default function faculty() {
    return (
      <div>
         <Head>
          <title>Faculty</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'Faculty'}></Header>
          <FacultyTable />
          <Fotter />
      </div>
    )
  }