import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js"
import Fest from "/components/festival/festPhotos.js";

export default function Festival() {
    return (
      <div>
         <Head>
          <title>Festival</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'Festival'}></Header>
          <Fest />
          <Fotter />
      </div>
    )
  }