import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js"
import ImageGallary from "/components/ImageGallary/ImageGallary.js";

export default function AboutUs() {
    return (
      <div>
         <Head>
          <title>Gallery</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'Gallery'}></Header>
          <ImageGallary />
          <Fotter />
      </div>
    )
  }