import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js"
import SchoolInfra from "/components/SchoolInfrastructure/SchoolInfra.js";

export default function SchoolInfrastructure() {
    return (
      <div>
         <Head>
          <title>School Infrastructure</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
          <Navbar/>
          <Header name={'School Infrastructure'}></Header>
          <SchoolInfra />
          <Fotter />
      </div>
    )
  }