import Head from 'next/head'
import Navbar from "/components/Navbar/NavbarElement.js"
import Header from "/components/Header/HeaderElement.js"
import Fotter from "/components/Fotter/Fotter.js"
import Strength from "/components/Strength/StrengthParticulars.js"

export default function StrengthPerticulars() {
    return (
      <div>
         <Head>
          <title>Strength Perticulars</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
            <Navbar/>
            <Header name={'Strength Perticulars'}></Header>
            <Strength />
            <Fotter />
      </div>
    )
  }